query QPodcast($slug: String!) {
    podcast(slug: $slug) {
        title, description, coverUrl, spotifyUrl, rssUrl
        episodes {
            title, description, createdAt, duration, mediaUrl
        }
    }
}
